### ISSUE TITLE
Can it work with IDistributedCache? 

### ISSUE THREAD

**Issue by DennisDyallo** [speige/AspNetCore.ResponseCaching.Extensions#1]
I want to have a distributed "output cache", I believe it's called ResponseCache nowdays. Where I'm at right now it would probably take me weeks to build an implementation. 
Is this possible? Feature request! :D

**Comment by speige** [comment]
You're correct .net core has renamed OutputCache to ResponseCache. The .net core implementation of ResponseCache is barebones & most people think it only handles HTTP caching headers. It also has a bug that it'll ignore the cache if the browser sends a no-cache or no-store header (which are common & make the OutputCache portion of ResponseCache almost useless). My branch fixes this bug & allows the ResponseCache to be persisted to disk so the cache is retained between app pool recycles. However, the cache will purged if a new version of the website is deployed.

I have not coded anything to make this distributed, but I do have some config settings exposed. You can probably modify them in your startup.cs to achieve what you need. If you need something more advanced, I don't have the time to code it right now. However, pull requests are welcome if you want to code it yourself.

As is, for each URL on your site, each of distributed servers would generate  a new response the 1st time a request came into that server, each would cache it separately on their local hard drive, and each would return a cached response the 2nd time.

If you don't want that initial 1st request to be slow, you can set up a "healtcheck / ping service" on your load balancer (Example: F5 BigIP ?) to "prime" the cache the 1st time. You'd need a separate private url for each server. Example: public = http://www.mysite.com, 2 private servers = http://server1.mysite.com and http://server2.mysite.com. Only 1 request per server is necessary to "prime" the cache, but it's common to repeat the request frequently to ensure the server hasn't crashed. A repeating healthCheck/ping will also re-"prime" the cache if a new version of the website is deployed.

If you don't want the wasted cpu cycles of generating the response the 1st time on multiple servers or you don't want to waste extra HDD space, you could modify the config to use a network drive for the cache.  Add this to your startup.cs in the ConfigureServices method
```
			services.AddDiskBackedMemoryResponseCaching((responseCachingOptions, diskBackedMemoryCacheOptions) =>
			{
				diskBackedMemoryCacheOptions.DiskCacheFolder = "\\sharedCacheUNCPath";
                                //you could also map a drive such as z:\ to \\sharedCacheUNCPath on each server if you prefer, but I don't think there's any benefit.
			});
```

If you prefer a database instead of network path there may be a tool that'll allow you to map a virtual network folder that instead goes to a database table. I've never researched this, but I bet it exists somewhere, but maybe not for your preferred database engine. I personally think a network path should be fine.

An additional benefit to using a shared network UNC path for DiskCacheFolder is you can "prime" the cache using a single healthCheck/ping request to each public URL, rather than one to each private server URL.

One caveat is if two servers get an identical request at the same time and a cache entry has not yet been generated, both servers will generate the full response and write it to the network cache, afterwords all servers will use the cache. If someone coded a true distributed cache they might choose to code a "locking" mechanism to make the 2nd server wait until the 1st server had finished generating the response. However, in my opinion it's better to avoid locking as much as possible for performance reasons, so if I chose to code a true distributed cache I'd be okay with generating the response 2x in this rare instance.

Does any of this help with what you needed?

**Comment by DennisDyallo** [comment]
Hi! And wow! Thanks for the super detailed response!! 

I also noticed the bug about the no-cache header (WHY ISNT THIS WORKIIIING 💢 haha)

Well I kind of wanted it to work with Redis as the distributed cache provider. I already have Redis in my infrastructure, and I was inspired by the dotnet core documentation.

But yeah, maybe I can use an UNC path instead! 
Thanks a lot for your StackOverflow response (that's where I found you) as well as this plugin. 

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1#using-a-redis-distributed-cache
